domains_to_model: [1,8]

lnd0aa_bounds: # Same for all domains (ln(1/seconds))
- -5.0
- 50.0

ea_bounds: # Same for all domains (kJ/mol)
- 50.0
- 500.0

# Below, indicate the diffusion geometry you'd like to use. Currently-supported options 
# are "plane sheet" and "spherical"
geometry: plane sheet

# Indicate the values you'd like to omit from the fitting exercise. 
# We use standard python indexing here--indexing begins at 0. 
# E.g. if you'd like to omit the 26th heating step in your experiment,
# you should write "[25]".
omit_value_indices: []

# Advanced settings below: 

# Degassing-too-early punishment: Some optimization-misfit-statistic combinations 
# may incentivize the model to degas far too early, especially when there are many 
# heating steps at the end of the experiment without much gas. We leave this off by default,
# but encourage the user to carefully examine the results of their optimzations.
punish_degas_early: false




