ea_bounds:
- 50.0
- 500.0
geometry: spherical
lnd0aa_bounds:
- -5.0
- 50.0
num_domains: 1
max_iters: 100000
misfit_stat: lnd0aa_chisq
omit_value_indices: []
punish_degas_early: true
temp_add: []
time_add: []
seed: 0
tol: 0.0001
popsize: 15
updating: deferred